# Generated by Django 4.0.1 on 2022-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_time',
            field=models.IntegerField(default=-1),
        ),
    ]
